### ISSUE TITLE
Decisão da palavra "var"

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [lucasfloriani/curso-de-programacao#1]
Por que decidiu usar `var` nos exemplos?
Acredito que uma forma melhor seja usar direto o `let`, e acostumar os novos programadores com as sintaxes/conceitos mais atuais - ainda mais pensando que os exemplos são baseados em typescript, ótima escolha inclusive.

Mas acho válido mostrar que existe o `var`.
Posso abrir uma PR se a issue fizer sentido aplicando as modificações no seu primeiro texto com exemplos, esse [aqui](https://github.com/lucasfloriani/curso-de-programacao/tree/main/004-variaveis-simples).

**Comment by lucasfloriani** [comment]
Opa @vit0rr obrigado por levantar essa questão!

Acabei escolhendo utilizar `var` pois gostaria de realizar uma outra aula onde abordaria sobre `let` e `const` e aproveitaria para explicar suas formas de uso em relação ao **contexto léxico** por exemplo, assim eu não precisaria abordar praticamente nada sobre o assunto no inicio e poderia fazer uma analogia entre `var` e `variável` que combina bem para os alunos entenderam para que serve.

Ainda estou com receio de colocar até pequenos detalhes a mais do que o conteúdo principal da aula, pois gostaria de deixar a aula o mais "limpa" possível para que assim os alunos não divergissem a atenção para esses detalhes que também são importantes, mas que talvez precisem de um momento certo para assim facilitar a compreensão.

**Comment by vitorsouzaalmeida** [comment]
Faz sentido, como é algo temporário, tudo ok, vou fechar a issue aqui, vlw @lucasfloriani
